### ISSUE TITLE
Failed to load the atom-import-cost-beta package

### ISSUE THREAD

**Issue by adnariMleinaD** [siddharthkp/atom-import-cost-beta#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-import-cost-beta](https://github.com/siddharthkp/atom-import-cost-beta) package 2.0.0

### Stack Trace

Failed to load the atom-import-cost-beta package

```
At Cannot find module 'import-cost'

Error: Cannot find module 'import-cost'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/atom-import-cost-beta/lib/main.js:7:19)
    at /packages/atom-import-cost-beta/lib/main.js:81:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:620607)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2964186)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2950897)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2949729)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2950470)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377113)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:375536)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:328072)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:375474)
    at t.loadState.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:640529)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-import-cost 1.2.0 
atom-import-cost-beta 2.0.0 
atom-wordpress 0.3.0 
atom-wpcodex 1.1.0 
autocomplete-wordpress-hooks 0.2.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
CMB-Snippets 0.1.3 
CodePress 0.3.0 
express-snippets 0.2.0 
expressjs 2.2.0 
hey-pane 1.1.2 
Hydrogen 2.6.0 
importcost 0.0.3 
impress 0.1.1 
local-server-express 0.3.1 
my-express-nodejs 0.0.10 
pinegrow-atom 0.3.1 
webflow-to-wordpress 0.0.2 
woocommerce 1.0.0 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-go-function 0.1.0 
wp-dev 0.3.5 
wp-functions-snippets 1.4.0 
zp-acf-snippets 0.4.0 
```

**Comment by siddharthkp** [comment]
You should probably be using https://github.com/siddharthkp/atom-import-cost
